[package]
authors = ["Daiki Nakashima <daiki48.engineer@gmail.com>"]
description = "tui file manager"
edition = "2021"
license = "MIT"
name = "dafi"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "*"
